# github workflow that fetches the latest version of the docker repository and runs the tests every day
name: Daily SQS External Policy Check
on:
  schedule:
    - cron: '0 0 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Bucket name'
        required: true
        default: 'moonactive-task-bucket'
      change_policy:
        description: 'Change policy'
        required: true
        default: 'false'
    
jobs:
    fetch-and-run:
      runs-on: ubuntu-latest
      steps:
          - name: Fetch the latest version of the repository
            uses: actions/checkout@v4
            
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Pull the latest version of the image
            run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sqs_policy_handler:latest

          - name: Run the script
            run: |
              set -xe
              docker run \
                -e AWS_DEFAULT_REGION=us-east-1 \
                -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
               ${{ secrets.DOCKERHUB_USERNAME }}/sqs_policy_handler:latest \
                --bucket ${{ github.event.inputs.bucket_name }} \
                --change-policy ${{ github.event.inputs.change_policy}}